version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "player:1:1:compact,match_event:1:1,player_event:1:1"
      LOG_CLEANER_ENABLE: "true"
      LOG_CLEANUP_POLICY: "compact"
      LOG_CLEANER_MIN_COMPACTION_LAG_MS: 100
      LOG_CLEANER_MAX_COMPACTION_LAG_MS: 1000
      DELETE_RETENTION_MS: 10000
#      KAFKA_LOG_RETENTION_MS: 1000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 10